name: Automerge

on:
 push:
     branches:
       - release/*

# env:
#   MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/mydevopsgithub/merge
#   MY_BRANCH: main
#   MASTER_REPO: https://github.com/mydevopsgithub/merge
# #   MASTER_BRANCH: github.ref


jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: main
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full git history

      # - name: Merge release
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     target_branch: main
      #     message: Merge release into main
      #     github_token: ${{ secrets.TOKEN_GITHUB }}

 
      - name: Setup Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
 
      - name: Checkout default branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is $CURRENT_BRANCH"
          
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
          git fetch origin ${{ env.DEFAULT_BRANCH }}
          git checkout ${{ env.DEFAULT_BRANCH }}

      - name: Create PR 
        run: |
            git merge --no-ff $CURRENT_BRANCH -m "Auto-merge $CURRENT_BRANCH into ${{ env.DEFAULT_BRANCH }}"
            echo "creating PR"
            gh pr create \
              --base "${{ env.DEFAULT_BRANCH }}" \
              --head "$CURRENT_BRANCH" \
              --title "Auto-merge $CURRENT_BRANCH into ${{ env.DEFAULT_BRANCH }}" \
              --body "Automated pull request created by Github Actions"
     
      - name: auto-merge PR
        run: |
            echo "Merge Pull request"
            gh pr merge --auto --merge
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} 
    
