
name: Automerge PR

on:
  # See note below about using pull_request_target
  pull_request:
    types:
      - opened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: automerge PR
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          
     
