name: Enable automerge PRs

on:
  # See note below about using pull_request_target
  pull_request:
     types: 
      - opened
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
     
